Варіант 2
1. Створіть масив із 200 елементів – значень чисельності населення 200 міст (припустимо,
що значення розподілені за нормальним законом із середнім 500 000 та стандартним
відхиленням 250 000).

In [ ]:
import numpy as np
p = np.random.normal(500000,250000, 200)
p

array([ 592523.92317581,  386851.02753541,  714596.92292355,
        393342.3632689 ,  365979.04498498,  543568.62618324,
        461926.68567204,  488403.02958846,  109629.38665601,
        317885.68108561,  126580.206442  ,  611598.95196371,
        520582.46303567,  845648.47668947,  148646.45350202,
        909902.45132272,  795003.13002117,  571852.28888597,
        128358.30216914,  270791.27985718,  201144.27518279,
          6537.40374739,  562992.49907751,  239762.90247548,
        821081.81274101,  518576.51286542,  603610.02330196,
        171819.27168218,  909355.87600204,  369328.99113307,
        496549.80532738,  416459.84152381,  526263.69949327,
       1205918.94813963,  710329.42978042,  520600.40734281,
        234686.5164308 ,  373844.75803196,  644900.13285642,
        367931.01141118,  212542.58123829,  458930.83832415,
        957096.79345476,  344437.53358101,  707019.87968393,
        336863.81425784,  670502.66668427,  322008.50125292,
        375742.69452372,

Округліть дані вниз до найближчого цілого.

In [ ]:
np.round(p, 2)

array([ 592523.92,  386851.03,  714596.92,  393342.36,  365979.04,
        543568.63,  461926.69,  488403.03,  109629.39,  317885.68,
        126580.21,  611598.95,  520582.46,  845648.48,  148646.45,
        909902.45,  795003.13,  571852.29,  128358.3 ,  270791.28,
        201144.28,    6537.4 ,  562992.5 ,  239762.9 ,  821081.81,
        518576.51,  603610.02,  171819.27,  909355.88,  369328.99,
        496549.81,  416459.84,  526263.7 , 1205918.95,  710329.43,
        520600.41,  234686.52,  373844.76,  644900.13,  367931.01,
        212542.58,  458930.84,  957096.79,  344437.53,  707019.88,
        336863.81,  670502.67,  322008.5 ,  375742.69,  706487.74,
        495396.59,  631979.65,  335811.79,  574891.8 ,  110083.16,
        367689.46,  759704.51,  307433.74,  753719.  ,  183843.26,
        205583.  ,  483007.64,  779512.18,  637230.97,  319568.78,
        587731.24,  793363.02,  755220.55,  463493.07, -159326.13,
        148822.39,  463708.88,  678865.64,  379049.21,  311037

Знайдіть мінімальну та максимальну чисельність населення за вибіркою.

In [ ]:
np.max(p)

1205918.9481396275

In [ ]:
np.min(p)

250705

Який відсоток міст має чисельність населення: а) не менше 800 000; б)менше 200 000
мешканців? Знайдіть номери цих міст.

In [ ]:
p[p<400000]

array([388281, 272164, 323483, 262888, 272666, 367844, 383150, 326481,
       269071, 366947, 332160, 377331, 299793, 265462, 304781, 276585,
       309704, 361442, 285928, 386245, 254688, 367259, 308243, 380764,
       251401, 377005, 315375, 319568, 289643, 253658, 274768, 328304,
       398901, 375378, 317237, 387046, 312278, 289951, 395918, 316528,
       301769, 359325, 385606, 264770, 316287, 268786, 302446, 371771,
       311517, 273511, 293363, 339613, 250705, 254373, 392828, 386111,
       372035, 289468, 302240, 334527, 329001, 290007, 272427, 280600,
       387441, 263528, 255238, 295046])

In [ ]:
(len(p[p<400000])/200)*100

34.0

In [ ]:
np.where(p<400000)

(array([  1,   2,   3,   4,   7,  12,  16,  18,  19,  23,  25,  27,  28,
         30,  31,  33,  34,  37,  38,  40,  41,  44,  47,  49,  51,  59,
         60,  62,  63,  72,  73,  75,  77,  86,  88,  94,  97,  98, 101,
        102, 104, 106, 114, 115, 117, 124, 128, 130, 132, 136, 143, 144,
        148, 152, 155, 157, 160, 165, 166, 167, 170, 174, 176, 181, 183,
        187, 196, 199]),)

In [ ]:
p[p>800000]

array([], dtype=int64)

In [ ]:
(len(p[p>800000])/200)*100

0.0

In [ ]:
np.where(p>800000)

(array([], dtype=int64),)

In [ ]:
p[p<200000]

array([], dtype=int64)

In [ ]:
(len(p[p<200000])/200)*100

0.0

In [ ]:
np.where(p<200000)

(array([], dtype=int64),)

Чи зустрічаються у вибірці міста з населенням понад мільйон?

In [ ]:
len(p[p>1000000])>0

True

Відсортуйте значення за зростанням. Розділіть дані на 4 рівні за величиною групи.
Створіть новий масив (копію), в якому значення з кожної групи закодовані числами -
номерами відповідних груп.

In [ ]:
x=np.sort(p)
x

array([255787, 258055, 259384, 259531, 277479, 283628, 285342, 287235,
       289813, 290921, 292695, 292747, 293268, 296713, 297881, 298467,
       300594, 302123, 302563, 302772, 304230, 305915, 307337, 308738,
       310047, 313943, 315812, 316159, 316870, 317727, 318106, 318476,
       319254, 319330, 319751, 323250, 327012, 330232, 341436, 342011,
       346003, 349660, 350462, 351344, 351891, 353342, 354669, 355205,
       356871, 359492, 359539, 359766, 360291, 366626, 370560, 371072,
       374952, 374981, 376977, 386166, 391442, 394243, 400974, 405910,
       407211, 407646, 408673, 411343, 411987, 415200, 416457, 416723,
       419830, 420353, 421382, 428653, 434367, 434964, 441153, 441613,
       447229, 448031, 450077, 453555, 453907, 457439, 458656, 459412,
       459665, 462922, 464213, 464520, 477556, 478206, 478370, 479569,
       485392, 489807, 502585, 506692, 509214, 510699, 510716, 516922,
       525173, 525329, 525988, 525995, 526492, 527371, 529534, 530857,
      

In [ ]:
a=x[:50].copy()# 1 group
a

array([250642, 250772, 253700, 256109, 257016, 257905, 258704, 260004,
       260906, 262049, 262449, 264548, 267752, 269864, 272618, 281298,
       281514, 282033, 290539, 291009, 291442, 295404, 298762, 300519,
       304567, 308759, 309176, 309785, 314005, 319791, 322383, 325575,
       330953, 331110, 333062, 334135, 334287, 334531, 335546, 335945,
       336001, 338354, 341093, 347651, 347913, 348519, 348842, 356981,
       356982, 360573])

In [ ]:
b=x[50:100].copy()# 2 group
b

array([361024, 365793, 366087, 369171, 369744, 371087, 376704, 380811,
       380820, 381668, 382203, 385507, 386727, 390566, 403769, 404355,
       405056, 405598, 412263, 421203, 425418, 426837, 427103, 427239,
       429339, 437317, 440484, 441799, 443690, 444151, 446889, 446927,
       448341, 451338, 452364, 452429, 455211, 461859, 462670, 466583,
       468164, 470522, 471166, 473275, 479406, 488451, 490156, 499052,
       499188, 499244])

In [ ]:
c=x[100:150].copy()# 3 group
c

array([500839, 503661, 505092, 510701, 512392, 521178, 523117, 528593,
       530008, 536517, 537425, 539905, 545006, 547851, 548800, 550948,
       552820, 553295, 554845, 557672, 559078, 559122, 565462, 567397,
       569316, 569443, 571117, 571475, 574474, 575289, 576684, 580687,
       581174, 581927, 586040, 590452, 590908, 593781, 600043, 600411,
       602481, 603169, 603999, 604593, 604957, 605381, 606939, 608993,
       611337, 612334])

In [ ]:
d=x[150:].copy()# 4 group
d

array([612578, 614645, 619002, 619609, 619760, 619834, 622951, 623790,
       625779, 628636, 638242, 638717, 638861, 641839, 647495, 649034,
       653337, 655502, 657646, 658581, 659490, 662738, 664637, 667525,
       667748, 669095, 670487, 670836, 671937, 674905, 676362, 680263,
       694789, 701163, 703959, 705890, 711725, 717378, 718937, 726765,
       727409, 728027, 730297, 730615, 734587, 735851, 746608, 747771,
       748254, 749673])

In [ ]:
a[a<360573]=1
print(a)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
b[b<499244]=2
print(b)



[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [ ]:
c[c<612334]=3
print(c)
c[c<=612334]=3
print(c)


[     3      3      3      3      3      3      3      3      3      3
      3      3      3      3      3      3      3      3      3      3
      3      3      3      3      3      3      3      3      3      3
      3      3      3      3      3      3      3      3      3      3
      3      3      3      3      3      3      3      3      3 612334]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [ ]:
d[d<749673]=4
print(d)
d[(d<=749673)&]=4
print(d)

[     4      4      4      4      4      4      4      4      4      4
      4      4      4      4      4      4      4      4      4      4
      4      4      4      4      4      4      4      4      4      4
      4      4      4      4      4      4      4      4      4      4
      4      4      4      4      4      4      4      4      4 749673]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4]


Додайте до вибірки ще 20 міст, населення яких – це випадкове ціле число між 50 000 та 1 000 000.

In [ ]:
m = np.random.randint(50000, 1000000, size=(20))
m

array([290703, 803126, 490229, 527875, 223981, 175697, 821854, 730074,
       265089, 243073, 391983, 588777, 385639, 775020, 782728, 720536,
       139609, 789124, 518169, 387593])

In [ ]:
y = np.concatenate([x, m])
print(y)

[255787 258055 259384 259531 277479 283628 285342 287235 289813 290921
 292695 292747 293268 296713 297881 298467 300594 302123 302563 302772
 304230 305915 307337 308738 310047 313943 315812 316159 316870 317727
 318106 318476 319254 319330 319751 323250 327012 330232 341436 342011
 346003 349660 350462 351344 351891 353342 354669 355205 356871 359492
 359539 359766 360291 366626 370560 371072 374952 374981 376977 386166
 391442 394243 400974 405910 407211 407646 408673 411343 411987 415200
 416457 416723 419830 420353 421382 428653 434367 434964 441153 441613
 447229 448031 450077 453555 453907 457439 458656 459412 459665 462922
 464213 464520 477556 478206 478370 479569 485392 489807 502585 506692
 509214 510699 510716 516922 525173 525329 525988 525995 526492 527371
 529534 530857 533710 533997 535774 538708 540090 541821 549819 550025
 553621 557288 558155 558735 559059 559101 559281 560600 561631 562061
 562399 565113 570131 570382 573186 578173 578590 580300 582018 585840
 58694