1. Створіть масив зі 100 елементів - значень віку деяких піддослідних (припустимо, що значення розподілені за рівномірним законом між 18 і 45 роками).

In [ ]:
import numpy as np
ages = np.random.randint(18, 46, 100)
ages

array([34, 32, 40, 31, 24, 39, 31, 34, 41, 37, 35, 22, 29, 20, 45, 38, 34,
       38, 43, 21, 22, 42, 18, 32, 27, 37, 27, 39, 31, 26, 27, 36, 21, 24,
       23, 37, 25, 21, 30, 40, 27, 21, 41, 42, 22, 34, 43, 34, 24, 19, 20,
       34, 44, 20, 33, 18, 42, 35, 40, 39, 23, 41, 29, 22, 35, 43, 25, 43,
       26, 23, 39, 37, 20, 21, 40, 41, 35, 30, 27, 29, 32, 45, 28, 29, 29,
       20, 22, 42, 23, 24, 30, 19, 42, 20, 42, 36, 24, 41, 44, 26])

Знайдіть середній та медіанний вік за вибіркою.

In [ ]:
avg = np.average(ages)
avg

31.32

In [ ]:
median = np.median(ages)
median

31.0

Знайдіть розмах (різниця між максимальним та мінімальним віком) вибірки.

In [ ]:
range = np.ptp(ages)
range

27

• Який відсоток піддослідних має вік: а) понад 30 років;

In [ ]:
older30 = np.sum(ages>30)
total = len(ages)
older30 / total * 100


52.0

• Який відсоток піддослідних має вік:  б) не більше 20 років?

In [ ]:
below_or_equal_20 = np.sum(ages<=20)
below_or_equal_20 / total * 100

10.0

Чи зустрічається у вибірці число 44?

In [ ]:
44 in ages

True

Відсортуйте значення зростання. Розділіть дані на три групи:
[18; x̅− σ); [x̅− σ; x̅+ σ]; (x̅+ σ; 45], где x̅–– середній вік, σ –– стандартне
відхилення. Створіть новий масив (копію), у якому значення з першої групи
закодовані числом 1, другої - числом 2, третьої - числом 3.

In [ ]:
sorted_ages = np.sort(ages)
sorted_ages

array([18, 18, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22,
       22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 26, 26, 26,
       27, 27, 27, 27, 27, 28, 29, 29, 29, 29, 29, 30, 30, 30, 31, 31, 31,
       32, 32, 32, 33, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 36, 36, 37,
       37, 37, 37, 38, 38, 39, 39, 39, 39, 40, 40, 40, 40, 41, 41, 41, 41,
       41, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 44, 44, 45, 45])

In [ ]:
deviation = np.std(ages)
deviation

8.084404739991683

Розділіть дані на три групи: [18; x̅− σ);

In [ ]:
first_group = sorted_ages[sorted_ages < median-deviation]
first_group

array([18, 18, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22,
       22, 22, 22])

[x̅− σ; x̅+ σ]

In [ ]:
first_step = sorted_ages[sorted_ages >= median-deviation]
middle_group = first_step[first_step <= median+deviation]
middle_group

array([23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 26, 26, 26, 27, 27, 27,
       27, 27, 28, 29, 29, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32, 32,
       33, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 36, 36, 37, 37, 37, 37,
       38, 38, 39, 39, 39, 39])

(x̅+ σ; 45]

In [ ]:
last_group = sorted_ages[sorted_ages > median+deviation]
last_group

array([40, 40, 40, 40, 41, 41, 41, 41, 41, 42, 42, 42, 42, 42, 42, 43, 43,
       43, 43, 44, 44, 45, 45])

Створіть новий масив (копію), у якому значення з першої групи закодовані числом 1, другої - числом 2, третьої - числом 3.

In [ ]:
encoded_ages = np.concatenate((np.repeat(1, len(first_group)), np.repeat(2, len(middle_group)), np.repeat(3, len(last_group))), axis=None)
encoded_ages

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

• Додайте до вибірки ще 10 піддослідних, вік кожного з яких –випадкове ціле число між 18 та 45.

In [ ]:
ages = np.concatenate((ages, np.random.randint(18,46, 10)))
ages

array([34, 32, 40, 31, 24, 39, 31, 34, 41, 37, 35, 22, 29, 20, 45, 38, 34,
       38, 43, 21, 22, 42, 18, 32, 27, 37, 27, 39, 31, 26, 27, 36, 21, 24,
       23, 37, 25, 21, 30, 40, 27, 21, 41, 42, 22, 34, 43, 34, 24, 19, 20,
       34, 44, 20, 33, 18, 42, 35, 40, 39, 23, 41, 29, 22, 35, 43, 25, 43,
       26, 23, 39, 37, 20, 21, 40, 41, 35, 30, 27, 29, 32, 45, 28, 29, 29,
       20, 22, 42, 23, 24, 30, 19, 42, 20, 42, 36, 24, 41, 44, 26, 37, 35,
       19, 42, 37, 22, 35, 43, 32, 38])

Створіть матрицю розміром 20×4 із нормального розподілу із середнім
μ = 0 та стандартним відхиленням σ = 2.5.
• Виведіть перші 5 рядків матриці.
• Виведіть останні 2 стовпці матриці.
• Знайдіть середнє значення а) у п'ятому рядку; б) у кожному рядку.
• Знайдіть максимальний елемент у першому стовпчику.
• Чи правильно, що подвійна сума елементів першого рядка більша, ніж сума
елементів останнього стовпця?
• Створіть нову матрицю того ж розміру, елементи якої обчислюються за правилом:
bij = max − aij , де aij - елементи вихідної матриці, max - її максимальний елемент.
• Знайдіть рядки, перший та останній елементи яких є позитивними.
• Знайдіть стовпці, середнє значення яких більше 0.5.
• Транспонуйте матрицю та видаліть з неї перші 5 стовпців.
• Додайте стовпець з одиниць (ліворуч) до матриці.
• Додайте до матриці п'ять нульових рядків (знизу).

In [ ]:
mean = 0
std_deviation = 2.5
matrix = np.random.normal(mean, std_deviation, (20, 4))
matrix


array([[-0.97273304, -4.0026301 , -0.87656306, -0.60575525],
       [ 2.9128048 ,  0.09490962,  0.47546642, -1.59372328],
       [ 4.61847138,  1.76418303, -5.8702299 , -1.67265171],
       [-1.19966001,  3.32519712, -4.01136469,  1.0543245 ],
       [-3.12014119,  3.03976208,  2.79967025, -3.99955624],
       [-2.18152164, -0.80939665, -1.02416086, -1.25812839],
       [-2.04840518, -1.08963443, -1.93121823,  2.38833742],
       [-2.02371434,  0.01320451, -0.84735489,  4.40363007],
       [ 5.39852472,  1.60664761, -1.47835664, -0.55334957],
       [-0.89576113, -1.49016008, -0.21603909,  0.22438768],
       [-1.64721378, -0.58291265,  4.35662797, -3.47777453],
       [-0.42712357, -2.73491927, -1.95247353, -1.42707306],
       [ 0.83067772, -1.17392823,  2.08234477,  1.51978293],
       [-0.29860065, -0.75226646,  5.14421274,  0.58739873],
       [-0.77731699,  4.51808219,  0.57123661, -0.17776923],
       [ 1.76755767, -0.41842464, -0.14126468,  1.82562968],
       [ 1.98692934,  0.

• Виведіть перші 5 рядків матриці.

In [ ]:
matrix[:5]

array([[-0.97273304, -4.0026301 , -0.87656306, -0.60575525],
       [ 2.9128048 ,  0.09490962,  0.47546642, -1.59372328],
       [ 4.61847138,  1.76418303, -5.8702299 , -1.67265171],
       [-1.19966001,  3.32519712, -4.01136469,  1.0543245 ],
       [-3.12014119,  3.03976208,  2.79967025, -3.99955624]])

Виведіть останні 2 стовпці матриці.

In [ ]:
matrix[:, -2:]

array([[-0.87656306, -0.60575525],
       [ 0.47546642, -1.59372328],
       [-5.8702299 , -1.67265171],
       [-4.01136469,  1.0543245 ],
       [ 2.79967025, -3.99955624],
       [-1.02416086, -1.25812839],
       [-1.93121823,  2.38833742],
       [-0.84735489,  4.40363007],
       [-1.47835664, -0.55334957],
       [-0.21603909,  0.22438768],
       [ 4.35662797, -3.47777453],
       [-1.95247353, -1.42707306],
       [ 2.08234477,  1.51978293],
       [ 5.14421274,  0.58739873],
       [ 0.57123661, -0.17776923],
       [-0.14126468,  1.82562968],
       [ 3.0422497 , -0.54736883],
       [-2.06131352,  0.27512293],
       [ 0.55320924, -3.65769848],
       [ 2.18617389,  3.43036942]])

Знайдіть середнє значення а) у п'ятому рядку;

In [ ]:
avg_5 = np.average(matrix[4])
avg_5

-0.320066275951879

б) у кожному рядку.

In [ ]:
common_avg = np.average(matrix)
common_avg

-0.016060381499273725

• Знайдіть максимальний елемент у першому стовпчику.

In [ ]:
max_1 = max(matrix[:, 0])
max_1

5.398524720930982

• Чи правильно, що подвійна сума елементів першого рядка більша, ніж сума елементів останнього стовпця?

In [ ]:
2*sum(matrix[0]) > sum(matrix[:, -1])

False

• Створіть нову матрицю того ж розміру, елементи якої обчислюються за правилом: bij = max − aij , де aij - елементи вихідної матриці, max - її максимальний елемент.

In [ ]:
new_matrix = np.array(np.max(matrix)- matrix)
new_matrix

array([[ 6.37125776,  9.40115482,  6.27508778,  6.00427998],
       [ 2.48571992,  5.3036151 ,  4.9230583 ,  6.992248  ],
       [ 0.78005334,  3.63434169, 11.26875462,  7.07117643],
       [ 6.59818473,  2.0733276 ,  9.40988941,  4.34420022],
       [ 8.51866591,  2.35876264,  2.59885447,  9.39808096],
       [ 7.58004637,  6.20792137,  6.42268558,  6.65665311],
       [ 7.4469299 ,  6.48815915,  7.32974295,  3.0101873 ],
       [ 7.42223906,  5.38532021,  6.24587961,  0.99489465],
       [ 0.        ,  3.79187712,  6.87688136,  5.95187429],
       [ 6.29428585,  6.8886848 ,  5.61456381,  5.17413704],
       [ 7.0457385 ,  5.98143737,  1.04189675,  8.87629925],
       [ 5.82564829,  8.13344399,  7.35099825,  6.82559778],
       [ 4.567847  ,  6.57245295,  3.31617995,  3.87874179],
       [ 5.69712537,  6.15079118,  0.25431198,  4.81112599],
       [ 6.17584171,  0.88044253,  4.82728811,  5.57629395],
       [ 3.63096705,  5.81694936,  5.5397894 ,  3.57289504],
       [ 3.41159538,  4.

• Знайдіть рядки, перший та останній елементи яких є позитивними.

In [ ]:
positive_half = new_matrix[new_matrix[:, 0] >0]
positive = positive_half[positive_half[:, -1] > 0]
positive

array([[ 6.37125776,  9.40115482,  6.27508778,  6.00427998],
       [ 2.48571992,  5.3036151 ,  4.9230583 ,  6.992248  ],
       [ 0.78005334,  3.63434169, 11.26875462,  7.07117643],
       [ 6.59818473,  2.0733276 ,  9.40988941,  4.34420022],
       [ 8.51866591,  2.35876264,  2.59885447,  9.39808096],
       [ 7.58004637,  6.20792137,  6.42268558,  6.65665311],
       [ 7.4469299 ,  6.48815915,  7.32974295,  3.0101873 ],
       [ 7.42223906,  5.38532021,  6.24587961,  0.99489465],
       [ 6.29428585,  6.8886848 ,  5.61456381,  5.17413704],
       [ 7.0457385 ,  5.98143737,  1.04189675,  8.87629925],
       [ 5.82564829,  8.13344399,  7.35099825,  6.82559778],
       [ 4.567847  ,  6.57245295,  3.31617995,  3.87874179],
       [ 5.69712537,  6.15079118,  0.25431198,  4.81112599],
       [ 6.17584171,  0.88044253,  4.82728811,  5.57629395],
       [ 3.63096705,  5.81694936,  5.5397894 ,  3.57289504],
       [ 3.41159538,  4.59474385,  2.35627502,  5.94589355],
       [ 8.92052113,  8.

Знайдіть стовпці, середнє значення яких більше 0.5

In [ ]:
column_means = np.mean(new_matrix, axis=0)
above05 = np.where(column_means > 0.5)[0]
above = new_matrix[:, above05]
above

array([[ 6.37125776,  9.40115482,  6.27508778,  6.00427998],
       [ 2.48571992,  5.3036151 ,  4.9230583 ,  6.992248  ],
       [ 0.78005334,  3.63434169, 11.26875462,  7.07117643],
       [ 6.59818473,  2.0733276 ,  9.40988941,  4.34420022],
       [ 8.51866591,  2.35876264,  2.59885447,  9.39808096],
       [ 7.58004637,  6.20792137,  6.42268558,  6.65665311],
       [ 7.4469299 ,  6.48815915,  7.32974295,  3.0101873 ],
       [ 7.42223906,  5.38532021,  6.24587961,  0.99489465],
       [ 0.        ,  3.79187712,  6.87688136,  5.95187429],
       [ 6.29428585,  6.8886848 ,  5.61456381,  5.17413704],
       [ 7.0457385 ,  5.98143737,  1.04189675,  8.87629925],
       [ 5.82564829,  8.13344399,  7.35099825,  6.82559778],
       [ 4.567847  ,  6.57245295,  3.31617995,  3.87874179],
       [ 5.69712537,  6.15079118,  0.25431198,  4.81112599],
       [ 6.17584171,  0.88044253,  4.82728811,  5.57629395],
       [ 3.63096705,  5.81694936,  5.5397894 ,  3.57289504],
       [ 3.41159538,  4.

Транспонуйте матрицю та видаліть з неї перші 5 стовпців

In [ ]:
trans = np.transpose(matrix)
trans
np.delete(trans, [1, 2,3,4,5], axis=1)

array([[-0.97273304, -2.04840518, -2.02371434,  5.39852472, -0.89576113,
        -1.64721378, -0.42712357,  0.83067772, -0.29860065, -0.77731699,
         1.76755767,  1.98692934, -3.52199641,  4.10736014,  1.37201994],
       [-4.0026301 , -1.08963443,  0.01320451,  1.60664761, -1.49016008,
        -0.58291265, -2.73491927, -1.17392823, -0.75226646,  4.51808219,
        -0.41842464,  0.80378087, -2.62494029, -1.40325432, -0.78727546],
       [-0.87656306, -1.93121823, -0.84735489, -1.47835664, -0.21603909,
         4.35662797, -1.95247353,  2.08234477,  5.14421274,  0.57123661,
        -0.14126468,  3.0422497 , -2.06131352,  0.55320924,  2.18617389],
       [-0.60575525,  2.38833742,  4.40363007, -0.55334957,  0.22438768,
        -3.47777453, -1.42707306,  1.51978293,  0.58739873, -0.17776923,
         1.82562968, -0.54736883,  0.27512293, -3.65769848,  3.43036942]])

Додайте стовпець з одиниць (ліворуч) до матриці

In [ ]:
new_trans = np.concatenate((np.full((len(trans), 1 ), 1), trans), axis=1)
new_trans

array([[ 1.        , -0.97273304,  2.9128048 ,  4.61847138, -1.19966001,
        -3.12014119, -2.18152164, -2.04840518, -2.02371434,  5.39852472,
        -0.89576113, -1.64721378, -0.42712357,  0.83067772, -0.29860065,
        -0.77731699,  1.76755767,  1.98692934, -3.52199641,  4.10736014,
         1.37201994],
       [ 1.        , -4.0026301 ,  0.09490962,  1.76418303,  3.32519712,
         3.03976208, -0.80939665, -1.08963443,  0.01320451,  1.60664761,
        -1.49016008, -0.58291265, -2.73491927, -1.17392823, -0.75226646,
         4.51808219, -0.41842464,  0.80378087, -2.62494029, -1.40325432,
        -0.78727546],
       [ 1.        , -0.87656306,  0.47546642, -5.8702299 , -4.01136469,
         2.79967025, -1.02416086, -1.93121823, -0.84735489, -1.47835664,
        -0.21603909,  4.35662797, -1.95247353,  2.08234477,  5.14421274,
         0.57123661, -0.14126468,  3.0422497 , -2.06131352,  0.55320924,
         2.18617389],
       [ 1.        , -0.60575525, -1.59372328, -1.67265171

Додайте до матриці п'ять нульових рядків (знизу).

In [ ]:
zero_rows = np.zeros((5, len(new_trans[0])))
zero_rows
trans_zero = np.concatenate((new_trans, zero_rows), axis=0)
trans_zero

array([[ 1.        , -0.97273304,  2.9128048 ,  4.61847138, -1.19966001,
        -3.12014119, -2.18152164, -2.04840518, -2.02371434,  5.39852472,
        -0.89576113, -1.64721378, -0.42712357,  0.83067772, -0.29860065,
        -0.77731699,  1.76755767,  1.98692934, -3.52199641,  4.10736014,
         1.37201994],
       [ 1.        , -4.0026301 ,  0.09490962,  1.76418303,  3.32519712,
         3.03976208, -0.80939665, -1.08963443,  0.01320451,  1.60664761,
        -1.49016008, -0.58291265, -2.73491927, -1.17392823, -0.75226646,
         4.51808219, -0.41842464,  0.80378087, -2.62494029, -1.40325432,
        -0.78727546],
       [ 1.        , -0.87656306,  0.47546642, -5.8702299 , -4.01136469,
         2.79967025, -1.02416086, -1.93121823, -0.84735489, -1.47835664,
        -0.21603909,  4.35662797, -1.95247353,  2.08234477,  5.14421274,
         0.57123661, -0.14126468,  3.0422497 , -2.06131352,  0.55320924,
         2.18617389],
       [ 1.        , -0.60575525, -1.59372328, -1.67265171