In [ ]:
import numpy as np

Створіть матрицю розміром 20 × 4 із рівномірного розподілу між −5 та 5.

In [ ]:
a = np.random.randint(-5, 5, size=(20, 4))
a

array([[-3, -1,  1, -2],
       [-1,  2, -3, -3],
       [-2,  2, -4, -4],
       [ 2, -3,  1, -2],
       [-1,  3,  2,  0],
       [ 3,  0,  3,  3],
       [-1,  4, -2,  2],
       [ 3,  4,  2,  2],
       [ 1,  1, -5,  0],
       [ 2,  0, -4,  1],
       [ 1, -5, -2, -4],
       [-4,  2,  2, -3],
       [-1, -2, -1,  2],
       [-5,  0, -4,  4],
       [-4,  4,  2,  0],
       [ 2, -4, -2, -1],
       [ 4,  2,  2, -5],
       [ 1,  2,  0, -5],
       [-2,  0, -4, -1],
       [-3, -5,  0, -3]])

Виведіть перші 10 рядків матриці.

In [ ]:
a[:10]

array([[-3, -1,  1, -2],
       [-1,  2, -3, -3],
       [-2,  2, -4, -4],
       [ 2, -3,  1, -2],
       [-1,  3,  2,  0],
       [ 3,  0,  3,  3],
       [-1,  4, -2,  2],
       [ 3,  4,  2,  2],
       [ 1,  1, -5,  0],
       [ 2,  0, -4,  1]])

Знайдіть суму двох останніх стовпців.

In [ ]:
sum(a)


array([ -8,   6, -16, -19])

In [ ]:
sum(a)[:2]


array([-8,  6])

In [ ]:
sum(a)[2:]

array([-16, -19])

Знайдіть мінімальне значення у п'ятому рядку.

In [ ]:
np.max(a, axis=1)[4]

3

Знайдіть середнє значення а) у першому стовпці; б) у кожному стовпці.

In [ ]:
np.mean(a, axis=0)[0] #a

-0.4

In [ ]:
np.mean(a, axis=0) #b

array([-0.4 ,  0.3 , -0.8 , -0.95])

Створіть нову матрицю того ж розміру, елементи якої обчислюються за правилом: :
bij = aij − mini, де aij - елементи вихідної матриці, mini- мінімальний елемент в i -му рядку.

Знайдіть рядки, середнє значення яких є негативним.

In [ ]:
a[np.mean(a, axis=1)<0] #b

array([[-3, -1,  1, -2],
       [-1,  2, -3, -3],
       [-2,  2, -4, -4],
       [ 2, -3,  1, -2],
       [ 1,  1, -5,  0],
       [ 2,  0, -4,  1],
       [ 1, -5, -2, -4],
       [-4,  2,  2, -3],
       [-1, -2, -1,  2],
       [-5,  0, -4,  4],
       [ 2, -4, -2, -1],
       [ 1,  2,  0, -5],
       [-2,  0, -4, -1],
       [-3, -5,  0, -3]])

In [ ]:
np.mean(a, axis=1)<0

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False, False,  True, False,
       False,  True])

Знайдіть стовпці, різниця між максимальним та мінімальним значенням у яких
більше 5.

In [ ]:
a[np.max(a, axis=1)-np.min(a, axis=1)>5]

array([[-2,  2, -4, -4],
       [-1,  4, -2,  2],
       [ 1,  1, -5,  0],
       [ 2,  0, -4,  1],
       [ 1, -5, -2, -4],
       [-4,  2,  2, -3],
       [-5,  0, -4,  4],
       [-4,  4,  2,  0],
       [ 2, -4, -2, -1],
       [ 4,  2,  2, -5],
       [ 1,  2,  0, -5]])

In [ ]:
np.max(a, axis=1)

array([1, 2, 2, 2, 3, 3, 4, 4, 1, 2, 1, 2, 2, 4, 4, 2, 4, 2, 0, 0])

In [ ]:
np.min(a, axis=1)

array([-3, -3, -4, -3, -1,  0, -2,  2, -5, -4, -5, -4, -2, -5, -4, -4, -5,
       -5, -4, -5])

In [ ]:
np.max(a, axis=1)-np.min(a, axis=1)>5

array([False, False,  True, False, False, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False])

Транспонуйте матрицю та видаліть з неї перші 5 стовпців.

In [ ]:
b=a.T
b

array([[-3, -1, -2,  2, -1,  3, -1,  3,  1,  2,  1, -4, -1, -5, -4,  2,
         4,  1, -2, -3],
       [-1,  2,  2, -3,  3,  0,  4,  4,  1,  0, -5,  2, -2,  0,  4, -4,
         2,  2,  0, -5],
       [ 1, -3, -4,  1,  2,  3, -2,  2, -5, -4, -2,  2, -1, -4,  2, -2,
         2,  0, -4,  0],
       [-2, -3, -4, -2,  0,  3,  2,  2,  0,  1, -4, -3,  2,  4,  0, -1,
        -5, -5, -1, -3]])

In [ ]:
delete = [15,16,17,18,19]
m = np.delete(b, delete, axis=1)
m

array([[-3, -1, -2,  2, -1,  3, -1,  3,  1,  2,  1, -4, -1, -5, -4],
       [-1,  2,  2, -3,  3,  0,  4,  4,  1,  0, -5,  2, -2,  0,  4],
       [ 1, -3, -4,  1,  2,  3, -2,  2, -5, -4, -2,  2, -1, -4,  2],
       [-2, -3, -4, -2,  0,  3,  2,  2,  0,  1, -4, -3,  2,  4,  0]])

Додайте до матриці стовпець одиниць (праворуч).

In [ ]:
one = np.array([[1],[1],[1],[1]])
print(one)

[[1]
 [1]
 [1]
 [1]]


In [ ]:
onem=np.hstack([m, one])
onem


array([[-3, -1, -2,  2, -1,  3, -1,  3,  1,  2,  1, -4, -1, -5, -4,  1],
       [-1,  2,  2, -3,  3,  0,  4,  4,  1,  0, -5,  2, -2,  0,  4,  1],
       [ 1, -3, -4,  1,  2,  3, -2,  2, -5, -4, -2,  2, -1, -4,  2,  1],
       [-2, -3, -4, -2,  0,  3,  2,  2,  0,  1, -4, -3,  2,  4,  0,  1]])

Додайте до матриці п'ять нульових рядків (згори).

In [ ]:
null = np.array([[-3 for j in range(15)] for i in range(4)])
null


array([[-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3]])

In [ ]:
 mnull=np.concatenate([null,m])
 mnull


array([[-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -1, -2,  2, -1,  3, -1,  3,  1,  2,  1, -4, -1, -5, -4],
       [-1,  2,  2, -3,  3,  0,  4,  4,  1,  0, -5,  2, -2,  0,  4],
       [ 1, -3, -4,  1,  2,  3, -2,  2, -5, -4, -2,  2, -1, -4,  2],
       [-2, -3, -4, -2,  0,  3,  2,  2,  0,  1, -4, -3,  2,  4,  0]])

Видаліть рядки, всі елементи яких є негативними.

In [ ]:
(mnull >= 0).all(axis=1)

array([ True,  True,  True,  True, False, False, False, False])

In [ ]:
mnull[(mnull <= 0).all(axis=1)]

array([[-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3]])

In [ ]:
mnull[(mnull >= 0).all(axis=1)]

array([], shape=(0, 15), dtype=int64)