In [ ]:
import numpy as np

# З'єднання масивів

In [ ]:
A = np.random.random(size=(10, 4))
B = np.random.randint(0, 10, size=(5, 4))

In [ ]:
print(A)
print(B)

[[0.81068984 0.50450912 0.89509225 0.84364828]
 [0.54352983 0.73579359 0.51524536 0.1485681 ]
 [0.19749398 0.56446302 0.60959095 0.57076223]
 [0.17729063 0.25181037 0.84403526 0.19092873]
 [0.69805696 0.94615424 0.30599001 0.33817938]
 [0.70220331 0.03962407 0.1041355  0.26972322]
 [0.73301092 0.18023027 0.9478867  0.15098074]
 [0.87883851 0.02346937 0.95765457 0.75206208]
 [0.13759813 0.88753286 0.67351713 0.12442138]
 [0.28284589 0.54859152 0.16210537 0.2531485 ]]
[[2 5 1 5]
 [8 4 6 4]
 [1 7 0 3]
 [2 9 7 8]
 [6 0 4 8]]


In [ ]:
C = np.concatenate([A, B])
print(C)

[[0.81068984 0.50450912 0.89509225 0.84364828]
 [0.54352983 0.73579359 0.51524536 0.1485681 ]
 [0.19749398 0.56446302 0.60959095 0.57076223]
 [0.17729063 0.25181037 0.84403526 0.19092873]
 [0.69805696 0.94615424 0.30599001 0.33817938]
 [0.70220331 0.03962407 0.1041355  0.26972322]
 [0.73301092 0.18023027 0.9478867  0.15098074]
 [0.87883851 0.02346937 0.95765457 0.75206208]
 [0.13759813 0.88753286 0.67351713 0.12442138]
 [0.28284589 0.54859152 0.16210537 0.2531485 ]
 [2.         5.         1.         5.        ]
 [8.         4.         6.         4.        ]
 [1.         7.         0.         3.        ]
 [2.         9.         7.         8.        ]
 [6.         0.         4.         8.        ]]


In [ ]:
D = np.concatenate([B, A])
print(D)

[[2.         5.         1.         5.        ]
 [8.         4.         6.         4.        ]
 [1.         7.         0.         3.        ]
 [2.         9.         7.         8.        ]
 [6.         0.         4.         8.        ]
 [0.81068984 0.50450912 0.89509225 0.84364828]
 [0.54352983 0.73579359 0.51524536 0.1485681 ]
 [0.19749398 0.56446302 0.60959095 0.57076223]
 [0.17729063 0.25181037 0.84403526 0.19092873]
 [0.69805696 0.94615424 0.30599001 0.33817938]
 [0.70220331 0.03962407 0.1041355  0.26972322]
 [0.73301092 0.18023027 0.9478867  0.15098074]
 [0.87883851 0.02346937 0.95765457 0.75206208]
 [0.13759813 0.88753286 0.67351713 0.12442138]
 [0.28284589 0.54859152 0.16210537 0.2531485 ]]


In [ ]:
E = np.random.random(size=(3, 3))
F = np.random.randint(0, 9, size=(3, 3))
G = np.concatenate([E, F])
print(G)

[[0.05899765 0.46557598 0.14127802]
 [0.68145928 0.93404919 0.49431644]
 [0.41476204 0.49392169 0.56105922]
 [4.         1.         2.        ]
 [3.         2.         2.        ]
 [4.         1.         1.        ]]


In [ ]:
H = np.concatenate([E, F], axis=1)
print(H)

[[0.05899765 0.46557598 0.14127802 4.         1.         2.        ]
 [0.68145928 0.93404919 0.49431644 3.         2.         2.        ]
 [0.41476204 0.49392169 0.56105922 4.         1.         1.        ]]


In [ ]:
I = np.random.randint(0, 9, size=(3, 4))
J = np.random.random(size=(5, 6))
K = np.concatenate([I, J])
print(K)

ValueError: ignored

In [ ]:
L = np.vstack([A, B])
print(L)

[[0.81068984 0.50450912 0.89509225 0.84364828]
 [0.54352983 0.73579359 0.51524536 0.1485681 ]
 [0.19749398 0.56446302 0.60959095 0.57076223]
 [0.17729063 0.25181037 0.84403526 0.19092873]
 [0.69805696 0.94615424 0.30599001 0.33817938]
 [0.70220331 0.03962407 0.1041355  0.26972322]
 [0.73301092 0.18023027 0.9478867  0.15098074]
 [0.87883851 0.02346937 0.95765457 0.75206208]
 [0.13759813 0.88753286 0.67351713 0.12442138]
 [0.28284589 0.54859152 0.16210537 0.2531485 ]
 [2.         5.         1.         5.        ]
 [8.         4.         6.         4.        ]
 [1.         7.         0.         3.        ]
 [2.         9.         7.         8.        ]
 [6.         0.         4.         8.        ]]


In [ ]:
M = np.vstack([B, A])
print(M)

[[2.         5.         1.         5.        ]
 [8.         4.         6.         4.        ]
 [1.         7.         0.         3.        ]
 [2.         9.         7.         8.        ]
 [6.         0.         4.         8.        ]
 [0.81068984 0.50450912 0.89509225 0.84364828]
 [0.54352983 0.73579359 0.51524536 0.1485681 ]
 [0.19749398 0.56446302 0.60959095 0.57076223]
 [0.17729063 0.25181037 0.84403526 0.19092873]
 [0.69805696 0.94615424 0.30599001 0.33817938]
 [0.70220331 0.03962407 0.1041355  0.26972322]
 [0.73301092 0.18023027 0.9478867  0.15098074]
 [0.87883851 0.02346937 0.95765457 0.75206208]
 [0.13759813 0.88753286 0.67351713 0.12442138]
 [0.28284589 0.54859152 0.16210537 0.2531485 ]]


In [ ]:
N = np.hstack([E, F])
print(N)

[[0.05899765 0.46557598 0.14127802 4.         1.         2.        ]
 [0.68145928 0.93404919 0.49431644 3.         2.         2.        ]
 [0.41476204 0.49392169 0.56105922 4.         1.         1.        ]]


In [ ]:
O = np.hstack([F, E])
print(O)

[[4.         1.         2.         0.05899765 0.46557598 0.14127802]
 [3.         2.         2.         0.68145928 0.93404919 0.49431644]
 [4.         1.         1.         0.41476204 0.49392169 0.56105922]]


# Проста аналітика для масивів

In [ ]:
path = "/content/drive/MyDrive/IT in Analytics/Python/Spring 2023/cardio_train.csv"
data = np.loadtxt(path, dtype=np.int32, delimiter=';', skiprows=1) # зчитали весь файл, окрім заголовка

<ipython-input-3-41a2b395668f>:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data = np.loadtxt(path, dtype=np.int32, delimiter=';', skiprows=1) # зчитали весь файл, окрім заголовка


In [ ]:
# Зчитуємо заголовок
with open(path, 'r') as f:
  header = f.readline()[:-1].split(';')
f.close()
print(header)

['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio']


In [ ]:
data.shape

(70000, 13)

In [ ]:
data.dtype

dtype('int32')

In [ ]:
# Порахуємо вік у роках
age = data[:, 1] // 365
data[:, 1] = age

In [ ]:
# Визначимо максимальний, мінімальний, середній вік пацієнтів
print(np.min(data[:, 1]))
print(np.max(data[:, 1]))
print(np.round(np.mean(data[:, 1]), 2))

29
64
52.84


In [ ]:
min(data[:, 1])

29

In [ ]:
%timeit min(data[:, 1])
%timeit np.min(data[:, 1])

7.3 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
118 µs ± 4.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Знайдемо мінімум та максимум по всім колонкам
print(np.min(data, axis=0))
print(np.max(data, axis=0))

[   0   29    1   55   10 -150  -70    1    1    0    0    0    0]
[99999    64     2   250   200 16020 11000     3     3     1     1     1
     1]


In [ ]:
# Який відсоток пацієнтів має ССЗ?
np.mean(data[:, -1])

0.4997

In [ ]:
cardio = data[:, -1]
print(cardio == 1)

[False  True  True ...  True  True False]


In [ ]:
# Застосовуємо логічну маску до масиву
cardio[cardio == 1]

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [ ]:
print(cardio[cardio == 1].shape[0] / data.shape[0])

0.4997


In [ ]:
people_with_cardio_problems = data[cardio == 1, :] # фільтр датасету
np.round(people_with_cardio_problems[:, 1].mean(), 2) #  середній вік пацієнтів із ССЗ

54.45

In [ ]:
# Знайдемо кількість людей зростом між 170 та 180 см
height = data[:, 3]
height[(height >= 170) & (height <= 180)].shape[0]

16575

In [ ]:
# Знайдемо пацієнтів вагою більше 100 кг
weight = data[:, 4]
overweight = data[weight > 100, :]

In [ ]:
np.mean(overweight[:, -1])

0.6917871424177177

In [ ]:
overweight[:, -1].mean()

0.6917871424177177

In [ ]:
%timeit overweight[:, -1].mean()
%timeit np.mean(overweight[:, -1])

12.8 µs ± 3.06 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.2 µs ± 3.39 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
