In [ ]:
import numpy as np

# Модификація масивів. Копії

In [ ]:
a = np.random.randint(0, 20, size=(5, 4))
a

array([[ 6, 10,  4,  5],
       [ 5, 18,  9,  5],
       [19,  8, 16, 16],
       [11,  8, 18, 18],
       [ 5,  3,  4, 14]])

In [ ]:
b = a[:2, :2]
b

array([[ 6, 10],
       [ 5, 18]])

In [ ]:
b[0, 0] = -1
b

array([[-1, 10],
       [ 5, 18]])

In [ ]:
a # як бачимо, при модифікації масиву b змінюється вихідний масив a

array([[-1, 10,  4,  5],
       [ 5, 18,  9,  5],
       [19,  8, 16, 16],
       [11,  8, 18, 18],
       [ 5,  3,  4, 14]])

In [ ]:
c = a[:2, :2].copy() # щоб цього не відбувалося, можна створити копію та змінювати копію
c

array([[-1, 10],
       [ 5, 18]])

In [ ]:
c[0, 0] = 0
c

array([[ 0, 10],
       [ 5, 18]])

In [ ]:
a # тоді зміна копії не зачіпає вихідний масив

array([[-1, 10,  4,  5],
       [ 5, 18,  9,  5],
       [19,  8, 16, 16],
       [11,  8, 18, 18],
       [ 5,  3,  4, 14]])

# З'єднання масивів

In [ ]:
x = np.array([1, 2, 3])
y = -x

In [ ]:
z = np.concatenate([x, y])
z

array([ 1,  2,  3, -1, -2, -3])

In [ ]:
x = np.random.random(size=(3, 4))
y = np.random.random(size=(6, 4))
print(x)
print(y)

[[0.92061289 0.88580422 0.01252198 0.2658807 ]
 [0.87432365 0.13339159 0.79947803 0.95261725]
 [0.1295483  0.4074857  0.28824501 0.05707222]]
[[0.36654282 0.0430386  0.87598054 0.34173322]
 [0.272242   0.95766954 0.60157671 0.21250261]
 [0.98111816 0.43602791 0.91106862 0.04947551]
 [0.64144424 0.43402698 0.93171158 0.04873089]
 [0.26759726 0.82138303 0.34288512 0.89959909]
 [0.51278678 0.5413659  0.7741161  0.0461899 ]]


In [ ]:
z = np.concatenate([x, y]) # з'єднання по першій розмірності
z

array([[0.92061289, 0.88580422, 0.01252198, 0.2658807 ],
       [0.87432365, 0.13339159, 0.79947803, 0.95261725],
       [0.1295483 , 0.4074857 , 0.28824501, 0.05707222],
       [0.36654282, 0.0430386 , 0.87598054, 0.34173322],
       [0.272242  , 0.95766954, 0.60157671, 0.21250261],
       [0.98111816, 0.43602791, 0.91106862, 0.04947551],
       [0.64144424, 0.43402698, 0.93171158, 0.04873089],
       [0.26759726, 0.82138303, 0.34288512, 0.89959909],
       [0.51278678, 0.5413659 , 0.7741161 , 0.0461899 ]])

In [ ]:
y1 = np.random.random(size=(3, 5))
print(y1)

[[0.69661199 0.75215315 0.93549484 0.30055201 0.4094829 ]
 [0.1715049  0.53737452 0.22710176 0.19436728 0.61194641]
 [0.3409072  0.91808564 0.17958526 0.46582108 0.62845408]]


In [ ]:
z1 = np.concatenate([x, y1], axis=1) # з'єднання по другій розмірності
print(z1)

[[0.92061289 0.88580422 0.01252198 0.2658807  0.69661199 0.75215315
  0.93549484 0.30055201 0.4094829 ]
 [0.87432365 0.13339159 0.79947803 0.95261725 0.1715049  0.53737452
  0.22710176 0.19436728 0.61194641]
 [0.1295483  0.4074857  0.28824501 0.05707222 0.3409072  0.91808564
  0.17958526 0.46582108 0.62845408]]


In [ ]:
z2 = np.hstack([x, y1]) # горизонтальне об'єднання
z2

array([[0.92061289, 0.88580422, 0.01252198, 0.2658807 , 0.69661199,
        0.75215315, 0.93549484, 0.30055201, 0.4094829 ],
       [0.87432365, 0.13339159, 0.79947803, 0.95261725, 0.1715049 ,
        0.53737452, 0.22710176, 0.19436728, 0.61194641],
       [0.1295483 , 0.4074857 , 0.28824501, 0.05707222, 0.3409072 ,
        0.91808564, 0.17958526, 0.46582108, 0.62845408]])

In [ ]:
z3 = np.vstack([x, y]) # вертикальне об'єднання
z3

array([[0.92061289, 0.88580422, 0.01252198, 0.2658807 ],
       [0.87432365, 0.13339159, 0.79947803, 0.95261725],
       [0.1295483 , 0.4074857 , 0.28824501, 0.05707222],
       [0.36654282, 0.0430386 , 0.87598054, 0.34173322],
       [0.272242  , 0.95766954, 0.60157671, 0.21250261],
       [0.98111816, 0.43602791, 0.91106862, 0.04947551],
       [0.64144424, 0.43402698, 0.93171158, 0.04873089],
       [0.26759726, 0.82138303, 0.34288512, 0.89959909],
       [0.51278678, 0.5413659 , 0.7741161 , 0.0461899 ]])

# Найпростіша аналітика для масивів

In [ ]:
x = np.random.normal(172.5, 5, 10000)
%timeit sum(x)
%timeit np.sum(x)

1000 loops, best of 5: 788 µs per loop
The slowest run took 7.25 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.62 µs per loop


In [ ]:
y = np.random.randint(0, 5, size=(5, 3))
y

array([[1, 3, 2],
       [3, 1, 3],
       [1, 2, 2],
       [3, 0, 3],
       [1, 2, 0]])

In [ ]:
sum(y)

array([ 9,  8, 10])

In [ ]:
np.sum(y)

27

In [ ]:
np.sum(y, axis=0) # сума по стовпцям

array([ 9,  8, 10])

In [ ]:
np.sum(y, axis=1) # сума за рядками

array([6, 7, 5, 6, 3])

In [ ]:
np.mean(y, axis=0) # середнє за стовпцями

array([1.8, 1.6, 2. ])

In [ ]:
np.max(y, axis=1) # максимум по рядкам

array([3, 3, 2, 3, 2])

# Broadcasting

In [ ]:
x = np.array(range(1, 10))
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

Больше примеров: [https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

# Логічне індексування

In [ ]:
x = np.random.normal(172.5, 5, 10)
x = np.round(x)
x

array([176., 164., 176., 174., 177., 174., 154., 166., 173., 166.])

In [ ]:
x > 175 # логічна маска

array([ True, False,  True, False,  True, False, False, False, False,
       False])

In [ ]:
x[x > 175] # ті елементи масиву х, які більше 175

array([176., 176., 177.])

In [ ]:
mask = (x > 160) & (x < 170) # маска з використанням двох умов одночасно
# & - AND, | - OR
mask

array([False,  True, False, False, False, False, False,  True, False,
        True])

In [ ]:
x[mask] # ті елементи масиву х, які задовольняють масці

array([164., 166., 166.])

In [ ]:
y = np.random.randint(0, 5, size=(5, 3))
y

array([[2, 0, 2],
       [3, 0, 4],
       [2, 1, 2],
       [2, 2, 3],
       [1, 2, 0]])

In [ ]:
mask = y[:, 1] == 0 # маска з умовою: елементи другого стовпця дорівнюють 0
mask

array([ True,  True, False, False, False])

In [ ]:
y[mask, :] # ті рядки з y, які задовольняють масці

array([[2, 0, 2],
       [3, 0, 4]])