# Вступ до бібліотеки NumPy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

## Одновимірні масиви

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
a

array([1, 2, 3])

In [ ]:
from random import random
x = [random() for i in range(10)]
a = np.array(x)
print(a)

[0.41614851 0.14025448 0.93978114 0.6000277  0.51720519 0.21223227
 0.24651857 0.23351797 0.83528422 0.96151611]


In [ ]:
len(a)

10

In [ ]:
a.size # довжина (кількість елементів)

10

In [ ]:
type(a) # тип

numpy.ndarray

In [ ]:
a.ndim # розмірність

1

In [ ]:
a.dtype # тип елементів масиву

dtype('float64')

In [ ]:
b = np.array([1, 2, '3', True])
print(b)

['1' '2' '3' 'True']


In [ ]:
b.dtype

dtype('<U21')

In [ ]:
c = np.array([1, 2, 3.5])
print(c)

[1.  2.  3.5]


In [ ]:
c.dtype

dtype('float64')

In [ ]:
d = np.array([1, 2, (3, 4)]) # так краще не робити
print(d)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
print(a)

[0.41614851 0.14025448 0.93978114 0.6000277  0.51720519 0.21223227
 0.24651857 0.23351797 0.83528422 0.96151611]


In [ ]:
a[0] = 0
print(a)

[0.         0.14025448 0.93978114 0.6000277  0.51720519 0.21223227
 0.24651857 0.23351797 0.83528422 0.96151611]


In [ ]:
a[:5]

array([0.        , 0.14025448, 0.93978114, 0.6000277 , 0.51720519])

In [ ]:
a[-5:]

array([0.21223227, 0.24651857, 0.23351797, 0.83528422, 0.96151611])

In [ ]:
a[3:7]

array([0.6000277 , 0.51720519, 0.21223227, 0.24651857])

In [ ]:
a[::-1]

array([0.96151611, 0.83528422, 0.23351797, 0.24651857, 0.21223227,
       0.51720519, 0.6000277 , 0.93978114, 0.14025448, 0.        ])

## Векторизовані операції

In [ ]:
from math import sin, pi
angles = [alpha for alpha in (0, pi/2, pi, 3*pi/2)]
sin_alpha = [sin(alpha) for alpha in angles]
print(angles)
print(sin_alpha)

[0, 1.5707963267948966, 3.141592653589793, 4.71238898038469]
[0.0, 1.0, 1.2246467991473532e-16, -1.0]


In [ ]:
angles_numpy = np.array(angles)
sin_alpha_numpy = np.sin(angles_numpy)

print(angles_numpy)
print(sin_alpha_numpy)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


In [ ]:
np.round(sin_alpha_numpy, 1)

array([ 0.,  1.,  0., -1.])

In [ ]:
2 * a

array([0.        , 0.28050897, 1.87956227, 1.20005539, 1.03441038,
       0.42446453, 0.49303714, 0.46703593, 1.67056844, 1.92303222])

In [ ]:
np.round(a, 2)

array([0.  , 0.14, 0.94, 0.6 , 0.52, 0.21, 0.25, 0.23, 0.84, 0.96])

In [ ]:
np.exp(3 * a - 5)

array([0.00673795, 0.01026273, 0.11296733, 0.04076559, 0.03179697,
       0.01273625, 0.01411603, 0.01357608, 0.08256682, 0.12057882])

## Двовимірні масиви

In [ ]:
d = np.array([[random() for j in range(4)] for i in range(5)])
print(d)

[[0.89253818 0.16358856 0.37500311 0.35756461]
 [0.1695519  0.00618738 0.97284841 0.79453899]
 [0.94085719 0.38159654 0.43734608 0.96456712]
 [0.49549834 0.1908515  0.07432648 0.21140389]
 [0.05628614 0.08581324 0.28939743 0.98231182]]


In [ ]:
len(d)

5

In [ ]:
d.size # кількість елементів у матриці (5*4)

20

In [ ]:
d.ndim

2

In [ ]:
d.shape

(5, 4)

In [ ]:
d.shape[0] # кількість рядків

5

In [ ]:
d.shape[1] # кількість стовпців

4

In [ ]:
d[1, 1] # звернення за індексом

np.float64(0.006187377939940286)

In [ ]:
d[:, 0] # доступ до стовпця

array([0.89253818, 0.1695519 , 0.94085719, 0.49549834, 0.05628614])

In [ ]:
d[3, :] # доступ до рядка

array([0.49549834, 0.1908515 , 0.07432648, 0.21140389])

In [ ]:
d[:2, :2] # доступ до частини матриці

array([[0.89253818, 0.16358856],
       [0.1695519 , 0.00618738]])

In [ ]:
np.linalg.det(d[:2, :2])

np.float64(-0.022214278819693775)

In [ ]:
d[:, 0].reshape((5, 1)) # перетворення рядка на стовпчик

array([[0.89253818],
       [0.1695519 ],
       [0.94085719],
       [0.49549834],
       [0.05628614]])

In [ ]:
d[:, 0].T

array([0.89253818, 0.1695519 , 0.94085719, 0.49549834, 0.05628614])

In [ ]:
np.cos(d)

array([[0.62743765, 0.98664921, 0.93050648, 0.93675197],
       [0.98566048, 0.99998086, 0.56294763, 0.70061379],
       [0.58909558, 0.92807126, 0.90587888, 0.56977267],
       [0.87973187, 0.98184307, 0.99723906, 0.9777373 ],
       [0.99841635, 0.9963203 , 0.95841601, 0.5551011 ]])

In [ ]:
e = np.random.random((4, 2))
print(e)

[[0.54858703 0.64291535]
 [0.90541598 0.83962271]
 [0.80781256 0.46751625]
 [0.74726081 0.02200535]]


In [ ]:
np.dot(np.cos(d), e) # матричне множення

array([[2.68920498, 1.68744284],
       [2.4244166 , 1.75190731],
       [2.32100988, 1.59401945],
       [2.9077929 , 1.87771178],
       [2.63882838, 1.93872061]])

In [ ]:
e * e # поелементне множення матриць

array([[3.00947730e-01, 4.13340153e-01],
       [8.19778105e-01, 7.04966300e-01],
       [6.52561136e-01, 2.18571445e-01],
       [5.58398716e-01, 4.84235300e-04]])